spring:
  boot:
    admin:
      client:
        url: http://localhost:8090
        username: admin
        password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always